---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-controller
  template:
    metadata:
      labels:
        app: chat-controller
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "chat"
        vault.hashicorp.com/agent-inject-secret-db: 'database/creds/writer'
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "database/creds/writer" -}}
            export username="{{ .Data.data.username }}"
            export password="{{ .Data.data.password }}"
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-pki: 'pki/issue/chat'
        vault.hashicorp.com/agent-inject-template-pki: |
          {{- with pkiCert "pki/issue/chat" "common_name=chat.local.jmpd.in" "ttl=2h" -}}
          {{ .Cert }}{{ .CA }}{{ .Key }}
          {{ .Key | writeToFile "/vault/secrets/cert.key" "vault" "vault" "0644" }}
          {{ .CA | writeToFile "/vault/secrets/cert.pem" "vault" "vault" "0644" }}
          {{ .Cert | writeToFile "/vault/secrets/cert.pem" "vault" "vault" "0644" "append" }}
          {{- end -}}
    spec:
      serviceAccountName: chat
      automountServiceAccountToken: true
      containers:
      - name: chat-controller
        image: guybarros/chat-app:latest
        args:
          ['sh', '-c', 'source /vault/secrets/config && npm start']
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_SERVER
          value: "10.100.0.180"
        - name: MONGODB_PORT
          value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-controller
spec:
  selector:
    app: chat-controller
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer