---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-default
  template:
    metadata:
      labels:
        app: chat-default
    spec:
      containers:
      - name: chat-app
        image: guybarros/chat-app:0.11
        ports:
        - containerPort: 5003
        env:
        - name: HTTP_PORT
          value: "5003"
        - name: MONGODB_SERVER
          value: "10.100.0.180"
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_AUTHDB
          value: "admin"
        - name: MONGODB_USERNAME
          value: "chat"
        - name: MONGODB_PASSWORD
          value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-csi
spec:
  selector:
    app: chat-default
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: LoadBalancer