---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-operator
  template:
    metadata:
      labels:
        app: chat-operator
      annotations:
       example: "annotations"
    spec:
      serviceAccountName: chat
      automountServiceAccountToken: true
      containers:
      - name: chat-app
        image: guybarros/chat-app:0.11
        ports:
        - containerPort: 5001
        env:
        - name: HTTP_PORT
          value: "5001"
        - name: MONGODB_SERVER
          value: "10.100.0.180"
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_AUTHDB
          value: "admin"
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: chat-database
              key: username
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: chat-database
              key: password
        - name: HTTP_TLS
          value: "true"
        - name: PRIVATE_KEY_PATH
          value: "/etc/ssl/certs/key.pem"
        - name: PUBLIC_CERT_PATH
          value: "/etc/ssl/certs/cert.pem"
        volumeMounts:
        - name: chat-pki
          mountPath: /etc/ssl/certs
          readOnly: true
      volumes:
        - name: chat-pki
          secret:
            secretName: chat-pki
            items:
            - key: certificate
              path: cert.pem
            - key: private_key
              path: key.pem

---
apiVersion: v1
kind: Service
metadata:
  name: chat-operator
spec:
  selector:
    app: chat-operator
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer