---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-csi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-csi
  template:
    metadata:
      labels:
        app: chat-csi
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "chat"
    spec:
      serviceAccountName: chat
      automountServiceAccountToken: true
      containers:
      - name: chat-csi
        image: guybarros/chat-app:latest
        ports:
        - containerPort: 5003
        env:
        - name: HTTP_PORT
          value: "5003"
        - name: MONGODB_SERVER
          value: "10.100.0.180"
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_AUTHDB
          value: "admin"
        - name: HTTP_TLS
          value: "true"
        - name: PRIVATE_KEY_PATH
          value: "/etc/ssl/certs/key.pem"
        - name: PUBLIC_CERT_PATH
          value: "/etc/ssl/certs/cert.pem"
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: vault-db-creds-secret
              key: username
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vault-db-creds-secret
              key: password
        volumeMounts:
          - name: 'vault-db-creds'
            mountPath: '/mnt/secrets-store'
            readOnly: true
          - name: 'vault-pki-creds'
            mountPath: '/etc/ssl/certs'
            readOnly: true
      volumes:
        - name: vault-db-creds
          csi:
            driver: 'secrets-store.csi.k8s.io'
            readOnly: true
            volumeAttributes:
              secretProviderClass: 'vault-db-creds'
        - name: vault-pki-creds
          csi:
            driver: 'secrets-store.csi.k8s.io'
            readOnly: true
            volumeAttributes:
              secretProviderClass: 'vault-pki-creds'

---
apiVersion: v1
kind: Service
metadata:
  name: chat-csi
spec:
  selector:
    app: chat-csi
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: LoadBalancer